services:
  db:
    image: mariadb:12
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "1"
      MARIADB_DATABASE: "taskdb"
      MARIADB_USER: "tasks"
      MARIADB_PASSWORD: "gW4nS2oH1cC7bQ8l"
    volumes:
      - ./db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      Database__type: "MySql"
      Database__host: "db:3306"
      Database__database: "taskdb"
      Database__user: "tasks"
      Database__password: "gW4nS2oH1cC7bQ8l"
      ASPNETCORE_ENVIRONMENT: dev
    depends_on:
      db:
        condition: service_healthy

  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "55801:80"
    depends_on:
      - api
