name: CI

on:
  push:
    branches: [main,tp3-inspection]
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          cache: true
          cache-dependency-path: backend/**/packages.lock.json

      - name: Restaurer les dépendances
        run: dotnet restore

      - name: Compiler
        run: dotnet build --no-restore --configuration Release

      - name: Tester avec couverture
        run: dotnet test api.slnx --no-restore --no-build --configuration Release --results-directory ./TestResults --report-xunit-trx --coverage --coverage-output-format cobertura

      - name: Résumé de couverture
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          badge: true
          filename: ./**/*.cobertura.xml
          fail_below_min: true
          thresholds: '60 80'
          format: markdown
          output: both

      - name: Ajouter au résumé du run
        if: always()
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        # ../code-coverage-results.md si vous avez le working directory à backend

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: backend/TestResults/**/*


  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Installer les dépendances
        run: yarn install --immutable

      - name: Construire
        run: yarn build

      - name: Lint
        run: yarn run lint

      - name: Vérifier le formatage
        run: dotnet format backend/api.slnx --verify-no-changes

      - name: Tester
        run: yarn test --ci --watchAll=false
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: front-build-output
          path: frontend/dist/
