name: CI
permissions:
  contents: read
on:
  push:
    branches: [main,tp3-inspection]
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          cache: true
          cache-dependency-path: backend/**/packages.lock.json

      - name: Restaurer les dépendances
        run: dotnet restore

      - name: Compiler
        run: dotnet build --no-restore --configuration Release

      - name: Tester avec couverture
        run: dotnet test api.slnx --no-restore --no-build --configuration Release --results-directory ./TestResults --report-xunit-trx --coverage --coverage-output-format cobertura

      - name: Résumé de couverture
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          badge: true
          filename: ./**/*.cobertura.xml
          fail_below_min: true
          thresholds: '40 60'
          format: markdown
          output: both

      - name: Ajouter au résumé du run
        if: always()
        run: cat ../code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        # ../code-coverage-results.md si vous avez le working directory à backend

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: backend/TestResults/**/*


  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Installer les dépendances
        run: yarn install --immutable

      - name: Construire
        run: yarn build

      - name: Lint
        run: yarn run lint

      - name: Vérifier le formatage
        run: dotnet format ../backend/api.slnx --verify-no-changes

      - name: Tester
        run: yarn test --ci --watchAll=false
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: front-build-output
          path: frontend/dist/
  securite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit npm
        working-directory: ./frontend
        run: corepack enable && yarn npm audit --severity high

      - name: Audit NuGet
        run: dotnet list backend/api.slnx package --vulnerable --include-transitive
        
     # Alternative plus simple pour l'audit nuget
     # dotnet restore -p:WarningsAsErrors="NU1903"

      - name: Construire l'image API
        run: docker build -t api:scan ./backend

      - name: Scanner l'image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'api:scan'
          severity: 'CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Construire l'image Web
        run: docker build -t web:scan ./frontend

      - name: Scanner l'image Web
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'web:scan'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

  publier:
    needs: [api, front, securite]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: docker.iut.arcanit.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publier l'API
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            docker.iut.arcanit.io/${{ secrets.DOCKER_USER }}/api:${{ github.sha }}
            docker.iut.arcanit.io/${{ secrets.DOCKER_USER }}/api:main

      - name: Publier le front
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            docker.iut.arcanit.io/${{ secrets.DOCKER_USER }}/web:${{ github.sha }}
            docker.iut.arcanit.io/${{ secrets.DOCKER_USER }}/web:main
  
  deployer-test:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Configurer SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VM_HOST }} -p ${{ secrets.VM_SSH_PORT }} >> ~/.ssh/known_hosts

      - name: Vérifier l'accès
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} -p ${{ secrets.VM_SSH_PORT }} \
            'docker version --format "{{.Server.Version}}"'
